### ISSUE TITLE
Mobile support?

### ISSUE THREAD

**Issue by johanholmerin** [FabianLars/tauri-v2-wgpu#2]
I wanted to get tauri and wgpu running together on mobile using this example(modified to match the tauri template: https://github.com/johanholmerin/tauri-v2-wgpu/commit/47fdbabe3bb685043e6b9094e8e1f56b12827682) but ran into some issues.

On iOS the wgpu rendered on top of the webview instead of behind it. Seems like there's some difference in behavior between platforms in either tauri or tao, but I don't know if this is a bug or not?

On android the app crashes immediately on start. Not sure what the issue is, might be that the [surface creation happens too early](https://github.com/gfx-rs/wgpu/wiki/Running-on-Android).

Let me know if I should move this issue over to the tauri repo

**Comment by FabianLars** [comment]
Yes please move this issue to the tauri repo.

This repo was supposed to be temporary to show something I was talking about on discord. I don't offer any kind of support here - speaking of support, mobile was indeed never looked at for this feature so this does not surprise me.

Thank you.
